# (DO NOT MOVE)

# Where the output log will be saved
outputDir 					= "output"

# Where the graph file is located
graphPath 					= "graphs/twitter_combined_WC.inf"

# This is the number of rounds (campaigns or trials) for seed generation.
trials 						= 4

# The seed-selection algorithm used.
algorithm 					= "maxdegree" # "celf/tim/maxdegree/discountdegree/pmc" (caps irrelevant)

# k-nodes that holds promising influence.
seeds 						= 25


model 						= "ic" # "IC/LT" (caps irrelevant)

# Number of simulations to be used by CELF, in literature, this is usually set to 10k.
simulations 				= 1000

# Seed that will be used for random number generation.
seed 						= 1487723611282
